spring.application.name=leave-service
server.port=${LEAVE_PORT:8084}
spring.datasource.url=${LEAVE_DB_URL:jdbc:postgresql://localhost:5432/leave_db}
spring.datasource.username=${LEAVE_DB_USER:leave_user}
spring.datasource.password=${LEAVE_DB_PASSWORD:leave_password}
spring.sql.init.mode=never
spring.jpa.show-sql=false
spring.mvc.problemdetails.enabled=true
jwt.access-public-key=${JWT_ACCESS_PUBLIC_KEY:file:../auth-service-main/keys/access-public.pem}
jwt.access-issuer=${JWT_ACCESS_ISSUER:auth-service}
jwt.access-audience=${JWT_ACCESS_AUDIENCE:hrm-api-access}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
