-- Run once on a new PostgreSQL database in a SQL editor or psql.
BEGIN;

CREATE TABLE calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL CHECK (length(btrim(title)) > 0),
    description TEXT,
    type VARCHAR(50) NOT NULL CHECK (type IN
        ('HOLIDAY', 'COMPANY_MEAL', 'TEAM_BUILDING', 'TRAINING',
         'MEETING', 'COMPANY_EVENT', 'OTHER')),
    holiday_kind VARCHAR(50),
    all_day BOOLEAN NOT NULL,
    start_date DATE,
    end_date DATE,
    start_at TIMESTAMPTZ,
    end_at TIMESTAMPTZ,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'
        CHECK (timezone = 'Asia/Ho_Chi_Minh'),
    location VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    audience_type VARCHAR(30) NOT NULL DEFAULT 'ALL'
        CHECK (audience_type = 'ALL'),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (all_day AND start_date IS NOT NULL AND end_date IS NOT NULL
            AND end_date >= start_date AND start_at IS NULL AND end_at IS NULL)
        OR
        (NOT all_day AND start_at IS NOT NULL AND end_at IS NOT NULL
            AND end_at > start_at AND start_date IS NULL AND end_date IS NULL)
    ),
    CHECK (
        (type = 'HOLIDAY' AND all_day AND holiday_kind IS NOT NULL
            AND holiday_kind IN ('PUBLIC_HOLIDAY', 'COMPANY_DAY_OFF', 'SUBSTITUTE_DAY_OFF'))
        OR (type <> 'HOLIDAY' AND holiday_kind IS NULL)
    )
);

CREATE TABLE calendar_event_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_event_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN
        ('CREATE', 'UPDATE', 'PUBLISH', 'CANCEL', 'DELETE')),
    actor_user_id VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(1000),
    before_data JSONB,
    after_data JSONB
);

CREATE INDEX calendar_events_all_day_range_idx
    ON calendar_events (start_date, end_date) WHERE all_day;
CREATE INDEX calendar_events_timed_range_idx
    ON calendar_events (start_at, end_at) WHERE NOT all_day;
CREATE INDEX calendar_event_audit_event_idx
    ON calendar_event_audit (calendar_event_id, occurred_at, id);

COMMIT;
