-- Fresh local-development database.
-- Run with psql as a PostgreSQL administrator.

-- DESTRUCTIVE:
-- deletes auth_db and all accounts / refresh sessions.

\set ON_ERROR_STOP on 
\connect postgres

-- ============================================================
-- APPLICATION ROLE
-- ============================================================

-- Create auth_user only if it doesn't already exist.
-- Do not drop cluster-wide roles.

SELECT
    'CREATE ROLE auth_user
     LOGIN
     NOSUPERUSER
     NOCREATEDB
     NOCREATEROLE
     NOREPLICATION
     PASSWORD ''auth_password'''
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'auth_user'
)
\gexec

-- ============================================================
-- DATABASE
-- ============================================================

DROP DATABASE IF EXISTS auth_db;

CREATE DATABASE auth_db OWNER auth_user;

-- Connect to new database
\connect auth_db

SET ROLE auth_user;

BEGIN;

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id uuid NOT NULL UNIQUE,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_key UNIQUE (email)
);

-- ============================================================
-- USER ROLES
-- ============================================================

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role varchar(20) NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_check CHECK (
        role IN (
            'EMPLOYEE',
            'MANAGER',
            'HR',
            'ADMIN'
        )
    )
);

-- ============================================================
-- REFRESH SESSIONS
-- ============================================================

CREATE TABLE refresh_sessions (
    id uuid PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX refresh_sessions_user_id_idx ON refresh_sessions (user_id);

COMMIT;

RESET ROLE;
