-- Complete Auth schema: accounts, roles, refresh sessions, Kafka and activation mail.
-- Run inside the target database as its owner (normally auth_user).
-- Plain SQL: no DROP DATABASE, no psql includes, no data reset, no automatic mail.
-- Intended for a fresh database; replay on this same schema is safe.
-- IF NOT EXISTS does not upgrade an incompatible older table definition.
-- Run with psql -X -v ON_ERROR_STOP=1 -f docs/sql/001_auth_schema.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    activation_pending BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pending_inactive CHECK (NOT activation_pending OR NOT is_active),
    CONSTRAINT users_employee_id_key UNIQUE (employee_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

-- Employee belongs to another service: no cross-database foreign key.
-- Account status is represented by is_active + activation_pending in Auth.
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_check CHECK (role IN ('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN'))
);

-- Sessions are created by login; do not seed raw tokens or fake refresh sessions.
CREATE TABLE IF NOT EXISTS refresh_sessions (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS refresh_sessions_user_id_idx ON refresh_sessions (user_id);

CREATE TABLE IF NOT EXISTS account_provisioning_results (
    request_id UUID PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    employee_id UUID NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    result_payload TEXT NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS account_link_versions (
    employee_id UUID PRIMARY KEY,
    version BIGINT NOT NULL CHECK (version > 0)
);

CREATE TABLE IF NOT EXISTS event_outbox (
    event_id UUID PRIMARY KEY,
    topic VARCHAR(200) NOT NULL,
    message_key VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claim_token UUID,
    lease_until TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS event_outbox_pending_idx ON event_outbox (sent_at, next_attempt_at);

CREATE TABLE IF NOT EXISTS account_activation_tokens (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CHECK (expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS activation_user_idx ON account_activation_tokens(user_id, created_at);
-- No plaintext token or activation URL with token. A stable secret held outside the
-- database derives the opaque token from the invitation ID for delivery/retries.
CREATE TABLE IF NOT EXISTS activation_mail_outbox (
    id UUID PRIMARY KEY REFERENCES account_activation_tokens(id),
    recipient VARCHAR(255) NOT NULL,
    sender VARCHAR(320) NOT NULL,
    activation_url VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'CANCELLED')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claim_token UUID,
    lease_until TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    provider_id VARCHAR(255),
    last_error VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS activation_mail_pending_idx ON activation_mail_outbox(status, next_attempt_at);

COMMIT;
