-- Active: 1790151670461@@127.0.0.1@5432@auth_db
-- RESET LOCAL DATABASE ONLY. Run with psql as a PostgreSQL administrator.
-- Deletes auth_db, including accounts and refresh sessions. Stop Auth first.
-- Does not terminate existing connections or drop cluster-wide roles.
-- Schema matches User, AuditableEntity, UserRole and RefreshSessions.
-- application.yaml uses ddl-auto: validate; start Auth after running this file.

\set ON_ERROR_STOP on
\connect postgres

SELECT 'CREATE ROLE auth_user LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD ''auth_password'''
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'auth_user')
\gexec

-- An existing auth_user keeps its password; align datasource credentials if needed.
-- PostgreSQL does not allow DROP/CREATE DATABASE inside a transaction.
DROP DATABASE IF EXISTS auth_db;
CREATE DATABASE auth_db OWNER auth_user;
\connect auth_db
SET ROLE auth_user;

BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_employee_id_key UNIQUE (employee_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

-- Employee belongs to another service: no cross-database foreign key.
-- Account status is represented by users.is_active, not Employee's accountStatus enum.
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_check CHECK (role IN ('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN'))
);

-- Sessions are created by login; do not seed raw tokens or fake refresh sessions.
CREATE TABLE refresh_sessions (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refresh_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX refresh_sessions_user_id_idx ON refresh_sessions (user_id);

COMMIT;
RESET ROLE;
