-- Run once against a new leave_db, as its owner. No cross-service foreign keys.
BEGIN;

-- Serializes submissions for an employee, including concurrent first requests.
CREATE TABLE leave_request_owners (
    employee_id UUID PRIMARY KEY
);

CREATE TABLE leave_requests (
    id UUID PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES leave_request_owners(employee_id),
    requester_user_id VARCHAR(255) NOT NULL,
    leave_type VARCHAR(30) NOT NULL CHECK (leave_type IN ('ANNUAL', 'UNPAID')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    leave_period VARCHAR(20) NOT NULL DEFAULT 'FULL_DAY'
        CHECK (leave_period IN ('FULL_DAY', 'MORNING', 'AFTERNOON')),
    total_units INTEGER NOT NULL CHECK (total_units > 0),
    reason VARCHAR(2000) NOT NULL CHECK (length(btrim(reason)) > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMPTZ,
    review_note VARCHAR(2000),
    CHECK (end_date >= start_date AND end_date - start_date < 366),
    CHECK (leave_period = 'FULL_DAY' OR start_date = end_date),
    CHECK ((status IN ('APPROVED', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
        OR (status IN ('PENDING', 'CANCELLED') AND reviewed_by IS NULL AND reviewed_at IS NULL)),
    CHECK (reviewed_by IS NULL OR reviewed_by <> requester_user_id),
    CHECK (status <> 'REJECTED' OR (review_note IS NOT NULL AND length(btrim(review_note)) > 0))
);
CREATE INDEX leave_requests_employee_created_idx ON leave_requests(employee_id, created_at DESC, id);
CREATE INDEX leave_requests_inbox_idx ON leave_requests(status, created_at DESC, id);
CREATE INDEX leave_requests_overlap_idx ON leave_requests(employee_id, start_date, end_date)
    WHERE status IN ('PENDING', 'APPROVED');

CREATE TABLE leave_request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL REFERENCES leave_requests(id),
    action VARCHAR(20) NOT NULL CHECK (action IN ('SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
    actor_user_id VARCHAR(255) NOT NULL,
    note VARCHAR(2000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX leave_request_history_request_idx ON leave_request_history(request_id, id);

-- One unit is half a day. The company policy grants 24 units (12 days) per calendar year.
CREATE TABLE leave_balances (
    employee_id UUID NOT NULL REFERENCES leave_request_owners(employee_id),
    year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 9999),
    entitled_units INTEGER NOT NULL DEFAULT 24 CHECK (entitled_units >= 0),
    used_units INTEGER NOT NULL DEFAULT 0 CHECK (used_units >= 0 AND used_units <= entitled_units),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (employee_id, year)
);
COMMIT;
